name: Generate Image JSON

on:
  push:
    branches:
      - main
    paths:
      - 'QuantumultX/*'
  workflow_dispatch:
    inputs:
      dummy-trigger:
        description: 'Dummy trigger for manual run'
        default: 'Run workflow'

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '16'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Node.js version
      run: node --version

    - name: Debug - Current working directory and list files
      run: |
        pwd
        ls -la
    - name: Generate JSON
      run: |
        IMAGES_FOLDER="icon"
        JSON_FILE="sliverkiss.icons.json"
        DESTINATION_FOLDER="QuantumultX"
        echo "Checking current directory:"
        pwd
        echo "Listing files in icon:"
        ls -al $IMAGES_FOLDER
        # Create an empty JSON file
        echo "[]" > $JSON_FILE
        # Create a JSON file header
        echo "{" > $JSON_FILE
        echo '  "name": "Sliverkiss图标订阅",' >> $JSON_FILE
        echo '  "description": "收集一些自己常用的图标 by @Sliverkiss",' >> $JSON_FILE
        echo '  "icons": [' >> $JSON_FILE
        
        # Populate the array with image information
        for FILE_PATH in $IMAGES_FOLDER/*; do
          if [ -f "$FILE_PATH" ]; then
            FILE_NAME=$(basename "$FILE_PATH")
            RAW_URL="https://raw.githubusercontent.com/Sliverkiss/QuantumultX/main/$FILE_PATH"
        # If it is not the first icon, add a comma at the end of the previous icon
          if [ "$FIRST_ITEM" = false ]; then
        # Add a comma to the end of the previous icon
            sed -i '$s/}$/},/' $JSON_FILE
          fi
    
            # Append image information to the JSON file
            echo -n ", " >> $JSON_FILE
            # Add image information to JSON file
            echo '  {' >> $JSON_FILE
            echo '    "name": "'$FILE_NAME'",' >> $JSON_FILE
            echo '    "url": "'$RAW_URL'"' >> $JSON_FILE
            echo '  },' >> $JSON_FILE
          fi
        done

            # Remove the last comma
            sed -i '$s/,$//' $JSON_FILE

            # Add JSON file at the end
            echo ']' >> $JSON_FILE
            echo '}' >> $JSON_FILE
            
        # Remove the leading comma
        sed -i 's/^\(.\{2\}\)//' $JSON_FILE

        echo "Checking generated JSON file:"
        cat $JSON_FILE
      
        # Set an environment variable with the path to the JSON file
        echo "ARTIFACT_PATH=QuantumultX" >> $GITHUB_ENV
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sliverkiss.icons.json
        path: ${{ env.ARTIFACT_PATH }}
    
    - name: Push JSON to Repository
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add QuantumultX/sliverkiss.icons.json
        git commit -m "Update sliverkiss.icons.json"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
